### PR TITLE
linters-setup

### PR DESCRIPTION
**Pull request by Prisca-tech**

### CODE REVIEW

**Comment by Prisca-tech** [comment]
This is my first pull request. I have implemented most of the professional rules and github-flows as well as attached linters, json packages, stylelintrc and hintrc. I added markup and style. I also tested the gitignore feature.

**Review by youmari — CHANGES_REQUESTED** [review]
Hi @Prisca-tech , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ Nice implementing the requirements

## Required Changes ♻️


- [ ] It would be better if you try to add a descriptive branch name, title, and short summary that tells in more detail what you've done in the Pull Request so that your PR will be professional and others can understand what your PR is about 

- In case you need to revisit the rules to write a professional PR I'll leave you the link [professional rules ](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md)
- Also next time please try to capitalize your commits messages following the rules  
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Prisca-tech** [comment]
Hello @youmari, 

To my understanding, I have added the linters and everything seems green unless I am missing something you can refer me to the exact line in my code.
 
I also feel like if I change the name of the branch I will have to create a new pull request. I will like suggestions on a suitable name for the branch and how to rename it without having to request a new PR

**Comment by Prisca-tech** [comment]
HI @youmari ,

Can i create a new branch and make new PR or edit the branch name and make a ne PR

**Comment by youmari** [comment]
> Hello @youmari,
> 
> To my understanding, I have added the linters and everything seems green unless I am missing something you can refer me to the exact line in my code.
> 
> I also feel like if I change the name of the branch I will have to create a new pull request. I will like suggestions on a suitable name for the branch and how to rename it without having to request a new PR

@Prisca-tech for the branch name try to implements to next time and for linters they are green I didn't notice I'll remove then from the required changes 
have a good luck

**Pull request closed without merging**
